// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _highprecHMM_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP calc_genprob(void *, void *, void *, void *, void *, void *, void *);
RcppExport SEXP calc_genprob_no_log(void *, void *, void *, void *, void *, void *, void *);
RcppExport SEXP est_hmm_map(void *, void *, void *, void *, void *, void *, void *);
RcppExport SEXP est_hmm_map_no_log(void *, void *, void *, void *, void *, void *, void *);

static const R_CallMethodDef CallEntries[] = {
    {"_highprecHMM_rcpp_hello_world", (DL_FUNC) &_highprecHMM_rcpp_hello_world, 0},
    {"calc_genprob",        (DL_FUNC) &calc_genprob,        7},
    {"calc_genprob_no_log", (DL_FUNC) &calc_genprob_no_log, 7},
    {"est_hmm_map",         (DL_FUNC) &est_hmm_map,         7},
    {"est_hmm_map_no_log",  (DL_FUNC) &est_hmm_map_no_log,  7},
    {NULL, NULL, 0}
};

RcppExport void R_init_highprecHMM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
